### PR TITLE
debug validator job

### PR DESCRIPTION
**Pull request by liusheng**

### CODE REVIEW

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Pull request closed without merging**
