### PR TITLE
Test cf openstack

### PR DESCRIPTION
**Pull request by animationzl**

### CODE REVIEW

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Pull request closed without merging**
